import type { Preset } from "./types";

export const PRESETS: Preset[] = [
  {
    key: "data-entry",
    label: "Data Entry",
    icon: "⌨️",
    automatability: "full",
    people: 2,
    minutesPerTask: 30,
    frequency: "daily",
    instancesPerPeriod: 1,
  },
  {
    key: "reports",
    label: "Report Generation",
    icon: "📊",
    automatability: "full",
    people: 1,
    minutesPerTask: 60,
    frequency: "weekly",
    instancesPerPeriod: 3,
  },
  {
    key: "quotes",
    label: "Quote Preparation",
    icon: "📋",
    automatability: "partial",
    people: 1,
    minutesPerTask: 45,
    frequency: "weekly",
    instancesPerPeriod: 5,
  },
  {
    key: "scheduling",
    label: "Scheduling & Appointments",
    icon: "📅",
    automatability: "full",
    people: 2,
    minutesPerTask: 20,
    frequency: "daily",
    instancesPerPeriod: 3,
  },
  {
    key: "payments",
    label: "Invoice & Payments",
    icon: "💰",
    automatability: "full",
    people: 1,
    minutesPerTask: 25,
    frequency: "weekly",
    instancesPerPeriod: 8,
  },
  {
    key: "faqs",
    label: "Answering FAQs",
    icon: "💬",
    automatability: "full",
    people: 3,
    minutesPerTask: 10,
    frequency: "daily",
    instancesPerPeriod: 5,
  },
  {
    key: "stock",
    label: "Inventory Checks",
    icon: "📦",
    automatability: "partial",
    people: 1,
    minutesPerTask: 40,
    frequency: "weekly",
    instancesPerPeriod: 2,
  },
];
